'''
from distutils.core import setup

setup(
    name='flex',
    version='0.1',
    packages=['flex', 'flex.flex', 'flex.flex.data', 'flex.flex.runs', 'flex.flex.config', 'flex.flex.models',
              'flex.flex.learners', 'flex.tests', 'flex.example', 'flex.example.data', 'flex.example.runs',
              'flex.example.utils', 'flex.example.models', 'flex.example.configs', 'flex.example.learners'],
    url='https://github.com/ahmadelsallab/flex',
    license='GNU',
    author='ahmad.elsallab',
    author_email='ahmad.elsallab@gmail.com',
    description='Framework for machine Learning EXperiment'
)
'''

import os
from setuptools import setup
from setuptools import find_packages
# requirements is generated by pipreqs <project_path>
with open('requirements.txt') as f:
    required = f.read().splitlines()


setup(
   name='flex',
   version='0.1',
   description='Framework for machine Learning EXperiment',
   author='Ahmad El Sallab',
   author_email='ahmad.elsallab@gmail.com',
   install_requires=required, #external packages as dependencies
   packages=find_packages()
)
